# Placeholder — cifrato con SOPS dall'orchestratore (sops --encrypt --in-place).
apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-url
    namespace: guazza
type: Opaque
stringData:
    HEALTHCHECKS_URL: ENC[AES256_GCM,data:Om4lz0QjoOQVXV0S4YL6qqcNUdaNWmGrROlTm5Ta,iv:lq9w1xDqSTvRunz9lS1/nespbfIT3foayOxNp1QqxCw=,tag:VPkWBBdAD6bUoBvhn2NASg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b3JKZGdYZzd5M05KN3dk
            ZkFmSWtnczA0OE9wcmt4VjkvN2wxaGFNdWtjCmw2Z2Zic2p4OUxNMlozbUFHaEJu
            NUYycDRQVDFRblB5Ny9JVUFpSUZKRzAKLS0tIE9KcHlvTVI3TWI5T1ljcWREVmNT
            K1ovQTRRWDVlUHZCK2VaNng5aFc3TDAKKUGWiOnaYPdJBrbMageSrvlgKKX4zV3f
            UKuxFIu0HGfXTZSKptCFyh8k7KqP5optlkgwjGB8EUpcPxi1X6Eqtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xha4vvyd2593c9cx2qnnzsfw7l5enj2yncvk3d9j62gsp0ql6y0qzmt6g5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T17:56:52Z"
    mac: ENC[AES256_GCM,data:k9aMe1RFzzKAv6F386aY5j7YaAm6vTQf8AJOfQ6sPqz9R41+mK9cmt6HsJY9ROpYnnkPi4UpeDGFqVePYUXRyfrQBcwa2vg0Q/CP/fTP/D5mOsAog+SmwvVXTlmaYKDL4TOqWr9th8yCAL7ryeKT2BPT49dSoemXVi01R7lUYKg=,iv:s8SB9W0X6vVaSPxmw8hXGMtv00uCPkpXklaLI0p/dgM=,tag:4jQW7tVa6AQIo+ZsNQwRpA==,type:str]
    version: 3.13.1
