apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjobs.yaml
  - netatmo-credentials.enc.yaml
  - healthchecks-url.enc.yaml
