# Placeholder — cifrato con SOPS dall'orchestratore (sops --encrypt --in-place).
apiVersion: v1
kind: Secret
metadata:
    name: netatmo-credentials
    namespace: guazza
type: Opaque
stringData:
    NETATMO_CLIENT_ID: ENC[AES256_GCM,data:ahzZK0IHLXhSxjvAZi5QNsHh5hV6SZun,iv:mu43OgABms7SwT46vV10QjBVIFXpYk2nbwDza+qxH94=,tag:mUekP2ICMQ8KrsmLdlhMcw==,type:str]
    NETATMO_CLIENT_SECRET: ENC[AES256_GCM,data:A9qX/nMhAPghfAqktFwJzaN/tnHWQ4duEfhj78/7OAXreLg=,iv:Xxi3mDNvWhPHFyMFWOjtRYvD9/wEXg9lQzJgdckpCAs=,tag:c+tDNDrFOy1ynqh2vxaEdA==,type:str]
    NETATMO_ACCESS_TOKEN: ENC[AES256_GCM,data:F0XLvVZwe4S+VqcNWG5L9PFnDn4vQrt+E1Mr9Y0UNgtvBPwYJBIDfM5WIYynAL2MbFO5nJD9txcb,iv:ozAFk6X9Vj3XqfroIJ2Ju12FNdHXRdo9JqBrAO2sf5Q=,tag:u1I9WE+pxgMsVAm9ndQsig==,type:str]
    NETATMO_REFRESH_TOKEN: ENC[AES256_GCM,data:X4HmDuZV1g4vJ9xjWiQFnWs6+/HK49r5I9XEaXjFmhOhUkfdvun+7OwW8v5sj2RHdy7/FCHQwjQt,iv:Pwa//OQPEMX7Eik9FGd5YdQRBoM0tQNOPsNXT8htNC0=,tag:7cQcw6BDPMAWBhEsXLLYtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTjY4aGZ3bDRsZXpaTjdw
            ZTRPYU11VUo1cEtkeWRTbXUvbExGcndaQjNrCjFNWEdzbVVBcEhoM0dueDFnMHRn
            c2RBWTZVSzBKMUk4UDE3cTRZT0ZudDgKLS0tIDV1cUUvSVVtV2U4SWZLM3p5MUVz
            TkZidnVzOHZ0WXhWaDF6M0VjLzJqak0KnTuHrCyJeGl4DH+pOAC6jEwQ0zv6MqQb
            U7tKhqjvu15OtavJrY4k/izbs5GVznv61iN87QndiANbMfIFmiNHQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xha4vvyd2593c9cx2qnnzsfw7l5enj2yncvk3d9j62gsp0ql6y0qzmt6g5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T17:24:55Z"
    mac: ENC[AES256_GCM,data:p6Sn8V6Gd1NpC4nVpwYUmu+s0lvl0p6vjAF0DhuZ5HCznzBZoHet//Q1Ktdpm7nS4t3sPdHQpKvU666EUFr+rOv1sJzKHXsHBiuUloQYubeGY5JrbmxBhEooRo4hStRxK8vlKsnlsWsfKG5vIurBhQ7kLNB5UBYf2DoIzX5L9d4=,iv:kfJKfQIFsMxfB8dIgV++cY4aWXQsSWW96MzFvd2Nank=,tag:VrfwB/I2tkliY3F+hcZqew==,type:str]
    version: 3.13.1
