apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guazza-data
  namespace: guazza
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
